# Generated by Django 5.0.3 on 2024-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_migrate_coordinates_to_point_20240526_0500'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coordinates',
            name='unique_latitude_longitude_altitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='longitude',
        ),
        migrations.AddConstraint(
            model_name='coordinates',
            constraint=models.UniqueConstraint(fields=('point', 'altitude'), name='unique_point_altitude'),
        ),
    ]
